### ISSUE TITLE
The output selector is wrong

### ISSUE THREAD

**Issue by yoanmalie** [jonathantneal/postcss-dir-pseudo-class#4]
Hi, I've found that the selector in the output is wrong.
We want to select blockquote who have a `dir` attribute set to `rtl` or `ltr`.
The selector given in the output say : We select blockquote who are child of element which have a `dir` attribute set to `rtl` or `ltr`.

Input:
```css
blockquote:dir(rtl) {
  margin-right: 10px;
}

blockquote:dir(ltr) {
  margin-left: 10px;
}
```

Output:
```css
[dir="rtl"] blockquote {
  margin-right: 10px;
}
[dir="ltr"] blockquote {
  margin-left: 10px;
}
```

Expected:
```css
blockquote[dir="rtl"] {
  margin-right: 10px;
}
blockquote[dir="ltr"] {
  margin-left: 10px;
}
```
